### ISSUE TITLE
Can't get it running with ruby 3.3.0 or 2.6.10

### ISSUE THREAD

**Issue by akoskm** [strzibny/asciidoc-book-template#1]
Hi Josef! I tried to give this template a shot, but I couldn't run it. I have `rbenv` on my system and here's what I get when trying to run `bundle install`:

```
$ ruby -v
ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [arm64-darwin23]
$ bundle install
Bundler 2.5.9 is running, but your lockfile was generated with 2.4.10. Installing Bundler 2.4.10 and restarting using that version.
Fetching gem metadata from https://rubygems.org/.
Fetching bundler 2.4.10
Installing bundler 2.4.10
[DEPRECATED] This Gemfile does not include an explicit global source. Not using an explicit global source may result in a different lockfile being generated depending on the gems you have installed locally before bundler is run. Instead, define a global source in your Gemfile like this: source "https://rubygems.org".
Resolving dependencies...
Your bundle is locked to foreman (0.87.2) from locally installed gems, but that version can no longer be found in that source. That means the author of foreman (0.87.2) has removed it. You'll need to update your bundle to a version other than foreman (0.87.2) that hasn't been removed
in order to install.
```

I switched to 2.6.10:
```
$ ruby -v
ruby 2.6.10p210 (2022-04-12 revision 67958) [universal.arm64e-darwin24]
$ bundle install
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:283:in `find_spec_for_exe': Could not find 'bundler' (2.4.10) required by your /Users/akoskm/Projects/asciidoc-book-template/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:2.4.10`
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:302:in `activate_bin_path'
        from /usr/bin/bundle:23:in `<main>'
```

after this I run `bundle update --bundler` which run successfully, but `bundle` still gives me the same error.

Can you help me with this?

**Comment by strzibny** [comment]
I tried to fix this with latest commits, can you try again? You shouldn't get the _This Gemfile does not include an explicit global source_ error anymore.

**Comment by tuladhar** [comment]
Works for me without any issue on:
```
 (master)> ruby -v
ruby 3.3.4 (2024-07-09 revision be1089c8ec) [arm64-darwin23]
 (master)>
```

**Comment by strzibny** [comment]
Great, thanks for checking @tuladhar I'll close for now.
